name: "M2 Coding Standard"
author: "Mage OS"
description: "A Github Action that runs the Magento Coding Standard."

inputs:
  php_version:
    type: string
    required: true
    default: "8.1"
    description: "PHP version used to do the coding standard check."

  composer_version:
    type: string
    required: true
    default: "2"
    description: "The version of composer to use."

  path:
    type: string
    required: true
    default: "app/code"
    description: "The directory (relative to the project root) in which the coding standard will be checked. Used when the event is not a pull request."

  version:
    type: string
    required: false
    default: "31"
    description: "The version of the coding standard to use. If not provided, will use the latest version."

  severity:
    type: string
    required: false
    default: "5"
    description: "The minimum severity required to display an error or warning (default: 5)"

  warning_severity:
    type: string
    required: false
    default: "5"
    description: "The minimum severity required to display a warning"

  error_severity:
    type: string
    required: false
    default: "5"
    description: "The minimum severity required to display an error"

  baseline_version:
    type: string
    required: false
    default: "1.1.2"
    description: "The version of the phpcs baseline to use. if not required it uses default one"

runs:
  using: composite
  steps:
    - name: Checkout Project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: standard

    - name: Set PHP Version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        tools: composer:v${{ inputs.composer_version }}
        coverage: none

    - name: Install Coding Standard && Codesniffer baseline
      shell: bash
      working-directory: standard
      run: |
        git config --global advice.detachedHead false
        composer require "magento/magento-coding-standard:${{ inputs.version || '*' }}"
        composer config --no-plugins allow-plugins.digitalrevolution/php-codesniffer-baseline true
        composer require --dev "digitalrevolution/php-codesniffer-baseline:${{ inputs.baseline_version }}"

    - name: Register Coding Standard
      shell: bash
      working-directory: standard
      run: vendor/bin/phpcs --config-set installed_paths ${{ github.workspace }}/standard/vendor/magento/magento-coding-standard,${{ github.workspace }}/standard/vendor/phpcompatibility/php-compatibility

    - name: Get all changed files
      id: changed-files
      uses: tj-actions/changed-files@v35

    - name: Checkout - Before Merge
      shell: bash
      working-directory: standard
      id: previous-commit-files
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
          git checkout ${{ github.event.pull_request.base.ref }}
        else
          git checkout ${{ github.event.before }}
        fi
        sed 's/ /\n/g' ${{ steps.changed-files.outputs.all_modified_files }}
        for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
          echo $file >> ${{ github.workspace }}/file_lists.txt
        done
        cat ${{ steps.changed-files.outputs.all_modified_files }}
        cat ${{ github.workspace }}/file_lists.txt

    - name: Filter php files and execute phpcs - Before Merge
      shell: bash
      id: phpcs_before
      working-directory: standard
      run: |
        grep -iE "\.php|\.phtml" ${{ github.workspace }}/file_lists.txt > ${{ github.workspace }}/phpcs_files.txt

        echo $(php vendor/bin/phpcs --standard=Magento2 \
        $([ -n "${{ inputs.severity }}" ] && echo "--severity=${{ inputs.severity }}") \
        $([ -n "${{ inputs.warning_severity }}" ] && echo "--warning-severity=${{ inputs.warning_severity }}") \
        $([ -n "${{ inputs.error_severity }}" ] && echo "--error-severity=${{ inputs.error_severity }}") \
        --report=\\DR\\CodeSnifferBaseline\\Reports\\Baseline --file-list=${{ github.workspace }}/phpcs_files.txt) > ${{ github.workspace }}/phpcs_old.xml

    - name: Checkout - After Merge
      shell: bash
      working-directory: standard
      id: latest-files
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
          git checkout ${{ github.event.pull_request.head.ref }}
        else
          git checkout ${{ github.event.after }}
        fi

        php vendor/bin/phpcs --standard=Magento2 \
        $([ -n "${{ inputs.severity }}" ] && echo "--severity=${{ inputs.severity }}") \
        $([ -n "${{ inputs.warning_severity }}" ] && echo "--warning-severity=${{ inputs.warning_severity }}") \
        $([ -n "${{ inputs.error_severity }}" ] && echo "--error-severity=${{ inputs.error_severity }}") \
        --report=\\DR\\CodeSnifferBaseline\\Reports\\Baseline --file-list=${{ github.workspace }}/phpcs_files.txt
