name: "Coding Standard"
author: "Graycore"
description: "A Github Action that runs the Magento Coding Standard."

inputs:
  php_version:
    required: true
    default: "8.1"
    description: "PHP version used to do the coding standard check."

  composer_version:
    required: true
    default: "2"
    description: "The version of composer to use."

  path:
    required: true
    default: "app/code"
    description: "The directory (relative to the project root) in which the coding standard will be checked. Used when the event is not a pull request."

  version:
    required: false
    default: "31"
    description: "The version of the coding standard to use. If not provided, will use the latest version."

  severity:
    required: false
    default: "5"
    description: "The minimum severity required to display an error or warning (default: 5)"

  warning_severity:
    required: false
    default: "5"
    description: "The minimum severity required to display a warning"

  error_severity:
    required: false
    default: "5"
    description: "The minimum severity required to display an error"

runs:
  using: composite
  steps:
    - name: Checkout Project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: project

    - name: Create Standard Directory
      shell: bash
      run: mkdir standard

    - name: Set PHP Version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        tools: composer:v${{ inputs.composer_version }}
        coverage: none

    - name: Install Coding Standard
      shell: bash
      working-directory: standard
      run: |
        composer require "magento/magento-coding-standard"
        composer config --no-plugins allow-plugins.digitalrevolution/php-codesniffer-baseline true
        composer require --dev "digitalrevolution/php-codesniffer-baseline"


    - name: Register Coding Standard
      shell: bash
      working-directory: standard
      run: ../.github/standard/vendor/bin/phpcs --config-set installed_paths ${{ github.workspace }}/standard/vendor/magento/magento-coding-standard,${{ github.workspace }}/standard/vendor/phpcompatibility/php-compatibility

    - name: Get Changed Files -TJ Actions
      id: change-files
      uses: tj-actions/changed-files@v35

    - name: Get list of changed files
      id: get_files
      shell: bash
      working-directory: project
      run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo 'file_changed=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }})' > files_changed.txt
          elif [ "${{ github.event_name }}" = "push" ]; then
        echo 'file_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})' > files_changed.txt
          fi

    - name: Filter PHP files
      id: filter_files
      shell: bash
      working-directory: project
      run: |
          grep '\.php$' files_changed.txt > files_php.txt

    - name: Get list of changed lines
      id: get_lines
      shell: bash
      working-directory: project
      run: |
        for file in ${{ steps.get_files.outputs.file_changed }}; do
            git diff -U0 "$file" | sed -n '/^@@/,/^diff/p' | tail -n +3 | grep -v '^[-+]' | cut -c2- > "${file}.lines"
          done < files_php_new.txt
          cat files_php_new.txt

    - name: Run PHPCS on changed lines
      id: run_phpcs
      shell: bash
      working-directory: project
      run: |
        while read file; do
          php ../.github/standard/vendor/bin/phpcs --standard=PSR2 --sniffs=PSR1.Files.SideEffects "$file" --lines=$(cat "${file}.lines" | tr '\n' ',')
        done < files_php.txt

    - name: List Old Changes
      shell: bash
      working-directory: project
      run: |
        for file in ${{ steps.change-files.outputs.all_changed_files }}; do
          git checkout HEAD~1 $file
          echo $(php ../.github/standard/vendor/bin/phpcs --standard=MageOs $file --report=xml) >> phpcs.baseline_old.xml
          cat phpcs.baseline_old.xml
          git checkout HEAD $file
          echo $(php ../.github/standard/vendor/bin/phpcs $file --report=xml --standard=MageOs) >> phpcs.baseline_new.xml
          cat phpcs.baseline_new.xml
        done


