name: M2 Coding Testing

on:
  push:
    branches: [ 2.4-develop, develop, phpcs_baseline ]
  pull_request:
    branches: [ 2.4-develop, develop, phpcs_baseline ]
  workflow_call:
    inputs:
      php_version:
        type: string
        required: true
        default: "8.1"
        description: "PHP version used to do the coding standard check."

      composer_version:
        type: string
        required: true
        default: "2"
        description: "The version of composer to use."

      path:
        type: string
        required: true
        default: 'app/code'
        description: "The directory (relative to the project root) in which the coding standard will be checked. Used when the event is not a pull request."

      version:
        type: string
        required: false
        description: "The version of the coding standard to use. If not provided, will use the latest version."

      severity:
        type: string
        required: false
        default: "8"
        description: "The minimum severity required to display an error or warning (default: 5)"

      warning_severity:
        type: string
        required: false
        default: "8"
        description: "The minimum severity required to display a warning"

      error_severity:
        type: string
        required: false
        default: "8"
        description: "The minimum severity required to display an error"

      baseline_version:
        type: string
        required: false
        default: "1.1.2"
        description: "The version of the phpcs baseline to use. if not required it uses default one"
permissions:
  contents: read

jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: project

      - name: Set PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}
          tools: composer:v${{ inputs.composer_version }}
          coverage: none

      - name: Install Coding Standard && Codesniffer baseline
        shell: bash
        working-directory: project
        run: |
          git config --global advice.detachedHead false
          composer require "magento/magento-coding-standard:${{ inputs.version || '*' }}"
          composer config --no-plugins allow-plugins.digitalrevolution/php-codesniffer-baseline true
          composer require --dev "digitalrevolution/php-codesniffer-baseline:${{ inputs.baseline_version || '^1.0' }}"

      - name: Register Coding Standard
        shell: bash
        working-directory: project
        run: vendor/bin/phpcs --config-set installed_paths ${{ github.workspace }}/standard/vendor/magento/magento-coding-standard,${{ github.workspace }}/standard/vendor/phpcompatibility/php-compatibility


      - name: Checkout project
        uses: actions/checkout@v2

      - name: Get all changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Checkout - Before Merge
        shell: bash
        id: previous-commit-files
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            git checkout ${{ github.event.pull_request.base.ref }}
          else
            git checkout ${{ github.event.before }}
          fi

          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo $file >> ${{ github.workspace }}/file_lists_old.txt
          done

      - name: Filter php,phtml files and execute phpcs - Before Merge
        shell: bash
        id: phpcs_before
        run: |
          grep -i "\.php$" ${{ github.workspace }}/file_lists_old.txt > ${{ github.workspace }}/file_php_old.txt
          grep -i "\.phtml$" ${{ github.workspace }}/file_lists_old.txt >> ${{ github.workspace }}/file_php_old.txt

          echo $(php vendor/bin/phpcs --standard=Magento2 \
          $([ -n "${{ inputs.severity }}" ] && echo "--severity=${{ inputs.severity }}") \
          $([ -n "${{ inputs.warning_severity }}" ] && echo "--warning-severity=${{ inputs.warning_severity }}") \
          $([ -n "${{ inputs.error_severity }}" ] && echo "--error-severity=${{ inputs.error_severity }}") \
          --report=\\DR\\CodeSnifferBaseline\\Reports\\Baseline --file-list=${{ github.workspace }}/file_php_old.txt) > ${{ github.workspace }}/phpcs_old.xml

      - name: Checkout - After Merge
        shell: bash
        id: latest-files
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
            git checkout ${{ github.event.pull_request.head.ref }}
          else
            git checkout ${{ github.event.after }}
          fi

          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo $file >> ${{ github.workspace }}/file_lists_new.txt
          done

      - name: Filter (php, phtml) files and execute phpcs - After Merge
        shell: bash
        id: phpcs_after
        run: |
          grep -i "\.php$" ${{ github.workspace }}/file_lists_new.txt > ${{ github.workspace }}/file_php_new.txt
          grep -i "\.phtml$" ${{ github.workspace }}/file_lists_new.txt >> ${{ github.workspace }}/file_php_new.txt

          php vendor/bin/phpcs --standard=Magento2 \
          $([ -n "${{ inputs.severity }}" ] && echo "--severity=${{ inputs.severity }}") \
          $([ -n "${{ inputs.warning_severity }}" ] && echo "--warning-severity=${{ inputs.warning_severity }}") \
          $([ -n "${{ inputs.error_severity }}" ] && echo "--error-severity=${{ inputs.error_severity }}") \
          --report=\\DR\\CodeSnifferBaseline\\Reports\\Baseline --file-list=${{ github.workspace }}/file_php_new.txt
