name: M2 Coding Testing

on:
  push:
    branches: [ 2.4-develop, develop, phpcs_test ]
  pull_request:
    branches: [ 2.4-develop, develop, phpcs_test ]


permissions:
  contents: read

jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Run Coding Standard
        uses: graycoreio/github-actions-magento2/coding-standard@main
        with:
          version: 25 # Optional, will use the latest if omitted.
          path: echo "files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT # Optional, will be used when event is not a pull request.

      - name: Get Changed Files
        shell: bash
        working-directory: standard
        id: changed-files
        run: echo "files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT

