name: M2 Coding Testing

on:
  push:
    branches: [ 2.4-develop, develop, phpcs_test ]
  pull_request:
    branches: [ 2.4-develop, develop, phpcs_test ]
  workflow_call:
    inputs:
      php_version:
        type: string
        required: true
        default: "8.1"
        description: "PHP version used to do the coding standard check."

      composer_version:
        type: string
        required: true
        default: "2"
        description: "The version of composer to use."

      path:
        type: string
        required: true
        default: 'app/code'
        description: "The directory (relative to the project root) in which the coding standard will be checked. Used when the event is not a pull request."

      version:
        type: string
        required: false
        description: "The version of the coding standard to use. If not provided, will use the latest version."

      severity:
        type: string
        required: false
        default: "8"
        description: "The minimum severity required to display an error or warning (default: 5)"

      warning_severity:
        type: string
        required: false
        default: "8"
        description: "The minimum severity required to display a warning"

      error_severity:
        type: string
        required: false
        default: "8"
        description: "The minimum severity required to display an error"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          printf "Hello\nWorld\n" > hw.txt

      - name: Create file
        run: |
          echo First        > other.txt
          echo Second Line >> other.txt
          echo Third       >> other.txt


      - name: List All Changed Files
        shell: bash
        run: |
          pwd
          echo "$(git diff --unified=0 --diff-filter=ACDMR HEAD^ HEAD | grep -v '^@@' | grep '^[+]' | grep -Ev '^(--- a/|\+\+\+ b/)')" > changed-lines.txt
          echo "233"
          cat changed-lines.txt


  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: './coding-standard'
        with:
          version: ${{ github.event.inputs.version || '*' }}
          path: ${{ github.event.inputs.path }}
