name: M2 Coding Testing

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
        default: '8.1'
  push:
    branches: [ 2.4-develop, develop, phpcs_baseline ]
  pull_request:
    branches: [ 2.4-develop, develop, phpcs_baseline ]

jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Install Coding Standard && Codesniffer baseline
        shell: bash
        run: |
          echo "Passed input: ${{ inputs.env_name }}"

