name: ExtDN M2 Coding Standard
on: [push, pull_request]



jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        dependencies:
          - "lowest"
          - "highest"
        severity:
          required: false
          default: "8"
          description: "The minimum severity required to display an error or warning (default: 5)"
        warning_severity:
          required: false
          default: "5"
          description: "The minimum severity required to display a warning"

        error_severity:
          required: false
          default: "5"
          description: "The minimum severity required to display an error"
        path:
          required: true
          default: 'app/code'
        exclude:
          - php-version: "8.1"
            dependencies: "lowest"
    name: Tests with PHP ${{ matrix.php-version }} and ${{ matrix.dependencies }} dependencies
    steps:
      - name: Install Coding Standards
        shell: bash
        working-directory: standard
        run: composer require "magento/magento-coding-standard:${{ inputs.version || '*' }}"

      - name: Run code style suite
        run: ../standard/vendor/bin/phpcs --standard=Magento2

      - name: Get Changed Files
        shell: bash
        working-directory: standard
        id: changed-files
        run: echo "files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
        if: github.event_name == 'pull_request'

      - name: Coding Standard Check
        shell: bash
        run: |
          ../standard/vendor/bin/phpcs --standard=Magento2 \
          $([ -n "${{ matrix.severity.default }}" ] && echo "--severity=${{ matrix.severity.default }}") \
          $([ -n "${{ matrix.warning_severity.default }}" ] && echo "--warning-severity=${{ matrix.warning_severity.default }}") \
          $([ -n "${{ matrix.error_severity.default }}" ] && echo "--error-severity=${{ matrix.error_severity.default }}") \
          ${{ github.event_name == 'pull_request' && steps.changed-files.outputs.files || matrix.path.default }}
          working-directory: project

  static:
    name: M2 Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-coding-standard@master

