name: "Code Inspection"
on:
  push:
    branches: [ 2.4-develop, develop, phpcs_test ]
    paths:
      - app/code
  pull_request:
    branches: [ 2.4-develop, develop, phpcs_test ]
    paths:
      - app/code
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
          path: app/code
      - run: |
          git diff ${{github.event.before}} ${{github.sha}}
