name: "Code Inspection"
on:
  push:
    branches: [ 2.4-develop, develop, phpcs_test ]
  pull_request:
    branches: [ 2.4-develop, develop, phpcs_test ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: app/code # you may customize glob as needed

      - name: Coding Standard Check
        shell: bash
        run: --standard=Magento2 ${{ github.event_name == 'pull_request' && steps.changed-files.outputs.files}}
        working-directory: project
